// INSTRUCTION: Please remove all comments that start INSTRUCTION prior to commit. Most comments should be removed, although not the copyright.
// INSTRUCTION: The copyright statement must appear at the top of the file
//
// Copyright (c) 2017, 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: istio-intro
:page-layout: guide-multipane
:page-duration: 30 minutes
:page-releasedate: 2019-02-01
:page-description: Explore how to manage microservice traffic using Istio.
:page-tags: ['Kubernetes', 'Docker']
:page-permalink: /guides/{projectid}
:page-related-guides: ['docker', 'kubernetes-intro', 'kubernetes-microprofile-config', 'kubernetes-microprofile-health']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
:page-seo-title: Managing microservice traffic using Istio
:page-seo-description: A tutorial on how to manage microservice traffic with Istio using blue-green deployment as an example
= Managing microservice traffic using Istio

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Explore how to manage microservice traffic using Istio.

:kube: Kubernetes
:istio: Istio
:win: WINDOWS
:mac: MAC
:linux: LINUX
:docker: Docker
:minikube: Minikube
:maven: Maven


== What you'll learn

You will learn how to deploy an application to a Kubernetes cluster and enable {istio} on it. You will also learn how to configure
{istio} to shift traffic to implement blue-green deployments for microservices.

=== What is {istio}?

https://istio.io/[{istio}] is a service mesh, meaning that it's a platform for managing
how microservices interact with each other and the outside world.
{istio} consists of a control plane and sidecars injected into application pods. The sidecars contain
the https://www.envoyproxy.io/[Envoy] proxy. You can think of Envoy as a sidecar that intercepts
and controls all the HTTP and TCP traffic to and from your container.

While {istio} runs on top of {kube} and that will be the focus of this guide, you can also use {istio} with
other environments such as https://docs.docker.com/compose/overview/[Docker Compose]. {istio} has many features such as
traffic shifting, request routing, access control, and distributed tracing, but the focus of this guide will be on traffic shifting.

=== Why {istio}?

{istio} provides a collection of features that allows you to manage several aspects of your services.
One example is {istio}'s routing features. You can route HTTP requests based on several factors such as HTTP headers or cookies.
Another use case for {istio} is telemetry, which you can use to enable distributed tracing. Distributed tracing allows you
to visualize how HTTP requests travel between different services in your cluster by using a tool such as https://www.jaegertracing.io/[Jaeger].
Additionally, as part of its collection of security features, {istio} allows you to enable mutual TLS between pods in your cluster.
Enabling TLS between pods secures communication between microservices internally.

You'll use {istio} to implement https://openliberty.io/guides/istio-intro.html#what-are-blue-green-deployments[blue-green deployments]. The traffic shifting feature allows you to allocate a percentage of
traffic to certain versions of services. You can use this feature to shift 100 percent of live traffic to blue deployments and 100 percent
of test traffic to green deployments. Then, you can shift the traffic to point to the opposite deployments as necessary to
perform blue-green deployments.

The microservice you'll deploy is called `hello`. It responds with a JSON object that has a version number and a greeting. The version number will be automatically incremented when you update the `pom.xml` version. This number will allow you to view which version of the microservice is running in your production or test environments.

=== What are blue-green deployments?

Blue-green deployments are a way of deploying your applications such that you have two environments where your application runs. In this scenario, you will have a production environment and a test environment. At any point in time, the blue deployment can accept production traffic and the green deployment can accept test traffic, or vice-versa. When you want to deploy a new version of your application, you will deploy to the color that is currently acting as your test environment. After the new version is verified on the test environment, the traffic will be shifted over. Thus, your live traffic is now being handled by what used to be the test site.

// =================================================================================================
// Prerequisites
// =================================================================================================

include::{common-includes}/kube-prereq.adoc[]

// =================================================================================================
// Getting Started
// =================================================================================================

[role=command]
include::{common-includes}/gitclone.adoc[]

// no "try what you'll build" section in this guide since it would be too long due to all setup the user will have to do.

// =================================================================================================
// Staring and preparing your cluster for deployment
// =================================================================================================

:minikube-start: minikube start --memory=8192 --cpus=4 --kubernetes-version=v1.10.0
[role=command]
include::{common-includes}/kube-start.adoc[]

// =================================================================================================
// Deploying Istio
// =================================================================================================

== Deploying Istio

First, go to the https://github.com/istio/istio/releases[{istio} release page] and download the latest stable release. Extract the archive and navigate to the directory with the extracted files.

Next, deploy the {istio} custom resource definitions. Custom resource definitions allow {istio} to define custom {kube} resources that you can use in your resource definition files.

[role=command]
```
kubectl apply -f install/kubernetes/helm/istio/templates/crds.yaml
```

Next, deploy {istio} resources to your cluster by running the `kubectl apply` command, which creates or updates
{kube} resources defined in a yaml file. This command will deploy {istio}.

[role=command]
```
kubectl apply -f install/kubernetes/istio-demo.yaml
```

Verify that {istio} was successfully deployed. All the values in the `AVAILABLE` column will have a value of `1` after
the deployment is complete.

[role=command]
```
kubectl get deployments -n istio-system
```
 
Ensure that the {istio} deployments are all available before you continue. The deployments might take a few minutes to become available. If the deployments aren't available after a few minutes, then increase the amount of memory available to your {kube} cluster. On Docker Desktop, you can increase the memory from your {docker} preferences. On {minikube}, you can increase the memory using the `--memory` flag.
[source, role="no_copy"]
----
NAME                     DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
grafana                  1         1         1            1           44s
istio-citadel            1         1         1            1           44s
istio-egressgateway      1         1         1            1           44s
istio-galley             1         1         1            1           44s
istio-ingressgateway     1         1         1            1           44s
istio-pilot              1         1         1            1           44s
istio-policy             1         1         1            1           44s
istio-sidecar-injector   1         1         1            1           44s
istio-telemetry          1         1         1            1           44s
istio-tracing            1         1         1            1           43s
prometheus               1         1         1            1           44s
servicegraph             1         1         1            1           44s
----

Finally, create the `istio-injection` label and set its value to `enabled`.

[role=command]
```
kubectl label namespace default istio-injection=enabled
```

Adding this label enables automatic {istio} sidecar injection. Automatic injection means that sidecars will
automatically be injected into your pods when you deploy your application. You don't need to perform
any additional steps for the sidecars to be injected.

// =================================================================================================
// Deploying v1
// =================================================================================================

== Deploying version 1 of the hello microservice

Navigate to the `start` directory and run the following command. It may take a few minutes to complete.
It will build the application and then package it into a {docker} image.
To build the {docker} image, it uses a {maven} plug-in called `dockerfile-maven-plugin`.

[role=command]
```
mvn clean package
```

The command builds a {docker} image for the `hello` microservice.
You can verify that this image was created by running the following command. 

[role=command]
```
docker images
```

You'll see an image called `hello:1.0-SNAPSHOT` listed in a table similar to the output.

[source, role="no_copy"]
----
REPOSITORY                 TAG            IMAGE ID       CREATED          SIZE
hello                      1.0-SNAPSHOT   d316c2c2c6ba   9 seconds ago    501MB
istio/galley               1.0.1          7ac6c7be3d3e   5 days ago       65.8MB
istio/citadel              1.0.1          abcc721c2454   5 days ago       51.7MB
istio/mixer                1.0.1          0d97b4000ed5   5 days ago       64.5MB
istio/sidecar_injector     1.0.1          a122adc160b7   5 days ago       45.3MB
istio/proxyv2              1.0.1          f1bf7b920fe1   5 days ago       352MB
istio/pilot                1.0.1          46d3b4e95fc3   5 days ago       290MB
open-liberty               latest         ed1ca62c4bd5   7 days ago       501MB
prom/prometheus            v2.3.1         b82ef1f3aa07   2 months ago     119MB
----

To deploy the `hello` microservice to the {kube} cluster, use the following command to deploy the microservice.

[role=command]
```
kubectl apply -f hello.yaml
```

You can see that your resources are created:

[source, role="no_copy"]
----
gateway.networking.istio.io/hello-gateway created
service/hello-service created
deployment.apps/hello-deployment-blue created
deployment.apps/hello-deployment-green created
destinationrule.networking.istio.io/hello-destination-rule created
----

hello.yaml
[source, yaml, linenums, role='code_column no_copy']
----
include::finish/hello.yaml[tags=**;]
----

View the [hotspot file=0]`hello.yaml` file. It contains two [hotspot=30-72 file=0]`deployments`, a [hotspot=17-28 file=0]`service`, a [hotspot=1-15 file=0]`gateway`, and a [hotspot=74-87 file=0]`destination rule`. One of the deployments is labeled [hotspot=30-50 file=0]`blue` and the second deployment is labeled [hotspot=52-72 file=0]`green`. The service points to both of these deployments. The {istio} gateway is the entry point for HTTP requests to the cluster. A destination rule is used to apply policies post-routing, in this situation it is used to define service subsets that can be specifically routed to.

start/traffic.yaml
[source, yaml, linenums, role='code_column no_copy']
----
include::start/traffic.yaml[tags=**;]
----

View the [hotspot file=1]`traffic.yaml` file. It contains two virtual services. A virtual service defines how requests are routed to your applications. In the virtual services, you can configure the weight, which controls the amount of traffic going to each deployment. In this case, the weights should be 100 or 0, which corresponds to which deployment is live.

Deploy the resources defined in the `traffic.yaml` file.

[role=command]
```
kubectl apply -f traffic.yaml
```

You can see that the virtual services have been created.

[source, role="no_copy"]
----
virtualservice.networking.istio.io/hello-virtual-service created
virtualservice.networking.istio.io/hello-test-virtual-service created
----

You can check that all of the deployments are available by running the following command.

[role=command]
```
kubectl get deployments
```

The command produces a list of deployments for your microservices that is similar to the following output.

[source, role="no_copy"]
----
NAME                     DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
hello-deployment-blue    1         1         1            1           1m
hello-deployment-green   1         1         1            1           1m
----

After all the deployments are available, you will make a request to v1 of the deployed application. As defined in the `hello.yaml` file the gateway is expecting the host to be `example.com`. However, requests to `example.com` won't be routed to the appropriate IP address. To ensure that the gateway routes your requests appropriately, ensure that the Host header is set to `example.com`. For instance, you can set the `Host` header with the `-H` option of the `curl` command.

****
[system]#*{win} | {mac}*#

Make a request to the service by running the following `curl` command.

[role=command]
```
curl -HHost:example.com http://localhost/hello
```

If the `curl` command is unavailable, then use https://www.getpostman.com/[Postman]. Postman enables you
to make requests using a graphical interface. To make a request with Postman, enter `http://localhost/hello`
into the URL bar. Next, switch to the `Headers` tab and add a header with key of `Host` and value of `example.com`.
Finally, click the blue `Send` button to make the request.

[system]#*{linux}*#

Make a request to the service by using `curl`.

[role=command]
```
curl -HHost:example.com http://`minikube ip`:31380/hello
```
****

You'll see a greeting message along with a corresponding version.

[source, role="no_copy"]
----
{"greeting":"hello","version":"1.0-SNAPSHOT"}
----

// =================================================================================================
// Deploy v2
// =================================================================================================

== Deploying version 2 of the hello microservice

The `hello` microservice is set up to respond with the version that is set in the `pom.xml` file. The tag for the {docker} image is also dependent on the version specified in the `pom.xml` file. Use the {maven} command to bump the version of the microservice to `2.0-SNAPSHOT`.

[role=command]
```
mvn versions:set -DnewVersion=2.0-SNAPSHOT
```

Build the new version of the {docker} container.

[role=command]
```
mvn clean package
```

Deploy the new image to the green deployment.

[role=command]
```
kubectl set image deployment/hello-deployment-green hello-container=hello:2.0-SNAPSHOT
```

You will work with two environments. One of the environments is a test site located at `test.example.com`. The other environment is your production environment located at `example.com`. To start with, the production environment is tied to the blue deployment and the test environment is tied to the green deployment.

Test the updated microservice by making requests to the test site. The `version` field in the response JSON is now `2.0-SNAPSHOT` on the test site and is still `1.0-SNAPSHOT` on the live site.

****
[system]#*{win} | {mac}*#

Make a request to the service by running the following `curl` command.

[role=command]
```
curl -HHost:test.example.com http://localhost/hello
```

If the `curl` command is unavailable, then use https://www.getpostman.com/[Postman].

[system]#*{linux}*#

Make a request to the service by using `curl`.

[role=command]
```
curl -HHost:test.example.com http://`minikube ip`:31380/hello
```
****

You'll see a greeting message along with a corresponding version.

[source, role="no_copy"]
----
{"greeting":"hello","version":"2.0-SNAPSHOT"}
----

After you see that the microservice is working on the test site, modify the [hotspot=17 hotspot=23 hotspot=41 hotspot=47]`weights` in the `traffic.yaml` file to shift 100 percent of the live traffic to the green deployment.

[role="code_command", subs="quotes"]
----
#Update the `traffic.yaml` file.#
`traffic.yaml`
----
finish/traffic.yaml
[source, yaml, linenums, role='code_column']
----
include::finish/traffic.yaml[tags=**;!copyright]
----

Deploy the updated `traffic.yaml` file.

[role=command]
```
kubectl apply -f traffic.yaml
```

Ensure that the live traffic is now being routed to version 2 of the microservice.

****
[system]#*{win} | {mac}*#

Make a request to the service by running the following `curl` command.

[role=command]
```
curl -HHost:example.com http://localhost/hello
```

If the `curl` command is unavailable, then use https://www.getpostman.com/[Postman].

[system]#*{linux}*#

Make a request to the service by using `curl`.

[role=command]
```
curl -HHost:example.com http://`minikube ip`:31380/hello
```
****

You'll see a greeting message along with a corresponding version.

[source, role="no_copy"]
----
{"greeting":"hello","version":"2.0-SNAPSHOT"}
----

== Testing microservices that are running on {kube}

Next, you will create a test to verify that the correct version of your microservice is running.

Create the endpoint test class in the `src/test/java/it/io/openliberty/guides/rest/EndpointTest.java` file:

[role="code_command", subs="quotes"]
----
#Create the `EndpointTest` class.#
`src/test/java/it/io/openliberty/guides/rest/EndpointTest.java`
----
EndpointTest.java
[source, Java, linenums, role='code_column']
----
include::finish/src/test/java/it/io/openliberty/guides/rest/EndpointTest.java[tags=**;!copyright]
----

The `testGetGreeting` test case verifies that the correct greeting and version number are returned from the rest service.

****
[system]#*{win} | {mac}*#

Run the command to start the tests:

[role=command]
```
mvn verify -Ddockerfile.skip=true
```

[system]#*{linux}*#

Run the command to start the tests:

[role=command]
```
mvn verify -Ddockerfile.skip=true -Dcluster.ip=`minikube ip` -Dport=31380
```

The `cluster.ip` and `port` parameters refer to the IP address and port for the {istio} gateway.
****

The `dockerfile.skip=true` flag skips rebuilding the {docker} images.

If the tests pass, then you should see output similar to the following example:

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.rest.EndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.648 s - in it.io.openliberty.guides.rest.EndpointTest

Results:

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
----

== Tearing down your environment

You might want to teardown all the deployed resources as a cleanup step.

Delete your resources from the cluster.

[role=command]
```
kubectl delete -f hello.yaml
kubectl delete -f traffic.yaml
```

Delete the `istio-injection` label from the default namespace. The hyphen immediately
after the label name indicates that the label should be deleted.

[role=command]
```
kubectl label namespace default istio-injection-
```

Navigate to the directory where you extracted {istio} and delete the {istio} resources from the cluster.

[role=command]
```
kubectl delete -f install/kubernetes/istio-demo.yaml
kubectl delete -f install/kubernetes/helm/istio/templates/crds.yaml
```

include::{common-includes}/kube-minikube-teardown.adoc[]

// =================================================================================================
// finish
// =================================================================================================

== Great work! You're done!

You have deployed a microservice that runs on Open Liberty to a Kubernetes cluster and used {istio} to implement a blue-green deployment scheme.

// uncomment this when Istio guide is released
//Feel free to check out our https://github.com/OpenLiberty/guide-istio[Istio guide], which builds on top of what you learned here.

// Include the below from the guides-common repo to tell users how they can contribute to the guide
include::{common-includes}/finish.adoc[]

include::https://raw.githubusercontent.com/OpenLiberty/guides-common/multipane/attribution.adoc[subs="attributes"]

// DO NO CREATE ANYMORE SECTIONS AT THIS POINT
// Related guides will be added in automatically here if you included them in ":page-related-guides"
